#!/usr/bin/env bash

set -euo pipefail

case $1 in
  __cached_setup)
    sed -i '' 's/"gcloud"/"gcloud-cached"/' "${HOME}/.docker/config.json"
    cat "${HOME}/.docker/config.json"
  ;;
  get)
    stdin=$(cat)
    if [ -f "/tmp/docker-credential-gcloud-${stdin}" ]; then
      if [ "$(find /tmp/docker-credential-gcloud-${stdin} -mmin +10)" = "" ]; then

        contents=$(cat "/tmp/docker-credential-gcloud-${stdin}")
        if [ "$contents" != "" ]; then
          echo "$contents"
          exit 0
        fi
      fi
    fi

    echo "$stdin" | docker-credential-gcloud get | tee "/tmp/docker-credential-gcloud-${stdin}"
  ;;
  *)
    echo "$@" > "/tmp/docker-credential-gcloud-wat"
    exit 1
  ;;
esac
