#!/usr/bin/env bash

set -euo pipefail

case $1 in
  get)
    stdin=$(cat)
    if [ "$(find /tmp/docker-credential-gcloud-${stdin} -mmin +10)" = "" ]; then
      cat "/tmp/docker-credential-gcloud-${stdin}"
      exit 0
    fi

    echo "$stdin" | docker-credential-gcloud get | tee "/tmp/docker-credential-gcloud-${stdin}"
  ;;
  *)
    echo "$@" > "/tmp/docker-credential-gcloud-wat"
    exit 1
  ;;
esac
